[package]
name = "shared"
version = "0.1.0"
authors = ["Benjamin Eder <barny.eder@gmail.com>"]
edition = "2018"
description = "Library crate containing shared components for the examples and tests"

[dependencies]
syntax-tree = {path = "../"}
